### ISSUE TITLE
iOS直播推流,rtmp能正常直播，RTC推流只有声音，画面黑屏

### ISSUE THREAD

**Issue by lilinmou** [tencentyun/XiaoZhiBo#17]
推流地址：trtc://cloud.tencent.com/push/111111?sdkappid=1400676964&userid=1111111&usersig=eJyrVgrxCdYrSy1SslIy0jNQ0gHzM1NS80oy0zLBwoYQAJUqTslOLCjITFGyMjQxMDAzN7M0M4HIpFYUZBalAsVNTU2NDAwMIKIlmbkgMTNTY0MjM3NTS6gpmelAk70Ck6M8SgoSXYz8onzTPKP8vPJCvV2TCyszckpdvAzLciMLq4KNLQvyY-STbZVqASRYMbQ_

时间:2022-06-06 13:4
[log.zip](https://github.com/tencentyun/XiaoZhiBo/files/8849411/log.zip)
0

**Comment by MinTate** [comment]
![image](https://user-images.githubusercontent.com/16069375/172117636-3c4a0d41-52ae-4c71-8414-6fe0bab80bd4.png)
主画面码率很低啊，分辨率：360*640d的时候，只有本身采集出来的画面是黑屏，才会有这种情况出现？
