### ISSUE TITLE
当我使用小直播安卓demo的时候，会出现如下报错

### ISSUE THREAD

**Issue by chenlang0311** [tencentyun/XiaoZhiBo#59]
![image](https://github.com/tencentyun/XiaoZhiBo/assets/30118413/9c8ceeeb-fa3d-48f3-a323-c023e372621b)

**Comment by chenlang0311** [comment]
已经按照文档https://cloud.tencent.com/document/product/454/38625中修改了配置。

**Comment by hash-panda** [comment]
你好，你的这个安卓可以运行成功么？我运行main 分支的代码，没有提示错误，直接 APP 奔溃了....
![image](https://github.com/tencentyun/XiaoZhiBo/assets/110599333/41411a23-5425-4199-afd0-46726f8c9c53)
![image](https://github.com/tencentyun/XiaoZhiBo/assets/110599333/5b8590ef-a52c-40a9-8059-72f4ae74a516)
